# Generated by Django 6.0.5 on 2026-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylog',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='study_date',
            field=models.DateField(verbose_name='学習日'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
